name: openid_client
description: Library for working with OpenID Connect and implementing clients.
version: 0.4.8
homepage: https://github.com/appsup-dart/openid_client
funding:
 - https://github.com/sponsors/rbellens

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jose: ^0.3.4
  pointycastle: ^3.7.3
  http: ^1.1.0
  logging: ^1.2.0
  args: ^2.4.2
  meta: ^1.9.1
  clock: ^1.1.1

dev_dependencies:
  test: ^1.24.5
  lints: ^2.1.1

executables:
  openid_client: openid_client
